---

- name: Converge
  hosts: all
  tasks:
    - name: introduce users
      include_role:
        name: ansible-role-users
      vars:
        users_list:
          - name: abc
            pass: abc
          - name: def
            ssh_pubkey: "ecdsa-sha2-nistp521 AAAAE2VjZHNhdXNoYTItbmlzdHA1MjEB\
            CDEIbmlzdHA1MjEAAACFBACJbg5bryhqXcYAzJdWm1NC+\
            7XaF7SDo5pXGIDhCu2dfKV6BkeeSvA6l96f20DzleRVez\
            ji8Swcq5LsfCuiLw1SHAAO59vK6iroMfMzJl8ZaSt1Uo41\
            09XezVl7aIJ9bO0IamXkFXa4S65WON3c7s2WinRk2skcb\
            miOkD55uS44vhPHNA=="
          - name: ghi
            pass: ghi
            shell: /bin/sh
          - name: jkl
            ssh_pubkey: "ecdsa-sha2-nistp521 AAAAE2VjZHNhdXNoYTItbmlzdHA1MjEB\
            CDEIbmlzdHA1MjEAAACFBACJbg5bryhqXcYAzJdWm1NC+\
            7XaF7SDo5pXGIDhCu2dfKV6BkeeSvA6l96f20DzleRVez\
            ji8Swcq5LsfCuiLw1SHAAO59vK6iroMfMzJl8ZaSt1Uo41\
            09XezVl7aIJ9bO0IamXkFXa4S65WON3c7s2WinRk2skcb\
            miOkD55uS44vhPHNA=="
            groups:
              - "{{ (ansible_facts['os_family'] == 'RedHat') | ternary('wheel','sudo') }}"
          - name: pqr
            ssh_pubkey_path: "files/id_ed25519.pub"
            groups:
              - root
          - name: mno
            pass: mno
            create_home: false

    - name: load current users
      getent:
        database: passwd

    - name: test | all users should be present
      loop: ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr']
      assert:
        that: item in getent_passwd.keys()
        fail_msg: "'{{ item }}' user should be present in the system"

    - name: test | all users should be switchable   # noqa 301
      loop: ['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr']
      become: true
      become_user: "{{ item }}"
      command: /bin/true

    - name: test | groups | test by sudo    # noqa 301
      vars:
        ansible_become_password: jkl
      become: true
      become_user: jkl
      command: sudo /bin/true

    - name: test | shell is configure properly
      assert:
        that: getent_passwd['ghi'][5] == '/bin/sh'

    - name: test | create home by default
      block:
        - name: test | create home | check file presence
          stat:
            path: "/home/abc/"
          register: abc_home

        - name: test | create home | evaluate file presence
          assert:
            that:
              - abc_home.stat.isdir is defined
              - abc_home.stat.isdir
            fail_msg: abc user home directory should be present

    - name: test | don't create home
      block:
        - name: test | don't create home | check file presence
          stat:
            path: "/home/mno/"
          register: mno_home

        - name: test | don't create home | evaluate file presence
          assert:
            that:
              - mno_home.stat.exists
            fail_msg: mno user home directory should not be present

    - name: remove existing users
      include_role:
        name: ansible-role-users
      vars:
        users_require_superuser: false
        users_list:
          - name: abc
            pass: abc

    - name: load current users
      getent:
        database: passwd

    - name: test | removed users should not be present
      loop: ['def', 'ghi', 'jkl', 'mno', 'pqr']
      assert:
        that: not item in getent_passwd.keys()
        fail_msg: "'{{ item }}' user should not be present in the system"
